import Contact from '@/components/Home/Contact/Contact';
import Greeting from '@/components/Home/Greeting/Greeting';
import Introduce from '@/components/Home/Introduce/Introduce';
import Projects from '@/components/Home/Projects/Projects';
import Skills from '@/components/Home/Skills/Skills';
import { Metadata } from 'next';
import { FaCaretDown } from 'react-icons/fa6';

export const metadata: Metadata = {
  title: "Ryan's Portfolio - Home",
  description: "Ryan's portfolio generated by next.js",
};

export default function Home() {
  return (
    <div className="mx-8 my-4">
      {/* Greeting */}
      <Greeting />
      <div className="flex justify-center">
        <a href="#intro">
          <FaCaretDown className="my-32 md:my-64 w-6 h-6 text-blue-400 animate-bounce" />
        </a>
      </div>
      {/* Introduce */}
      <Introduce />
      <div className="flex justify-center">
        <a href="#skills">
          <FaCaretDown className="my-16 md:my-4 w-6 h-6 text-blue-400 animate-bounce" />
        </a>
      </div>
      {/* Skills */}
      <Skills />
      <div className="flex justify-center">
        <a href="#projects">
          <FaCaretDown className="my-6 w-6 h-6 text-blue-400 animate-bounce" />
        </a>
      </div>
      {/* Projects */}
      <Projects />
      <div className="flex justify-center">
        <a href="#contact">
          <FaCaretDown className="my-16 w-6 h-6 text-blue-400 animate-bounce" />
        </a>
      </div>
      <Contact />
    </div>
  );
}
