import Contact from '@/components/Home/Contact/Contact';
import GoDown from '@/components/Home/GoDown';
import Greeting from '@/components/Home/Greeting/Greeting';
import Introduce from '@/components/Home/Introduce/Introduce';
import Projects from '@/components/Home/Projects/Projects';
import Skills from '@/components/Home/Skills/Skills';
import { Metadata } from 'next';
import { FaCaretDown } from 'react-icons/fa6';

export const metadata: Metadata = {
  title: "Ryan's Portfolio - Home",
  description: "Ryan's portfolio generated by next.js",
};

export default function Home() {
  return (
    <div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-5xl py-8">
      {/* Greeting */}
      <Greeting />
      <GoDown sectionName="intro" />
      {/* Introduce */}
      <Introduce />
      <GoDown sectionName="skills" />
      {/* Skills */}
      <Skills />
      <GoDown sectionName="projects" />
      {/* Projects */}
      <Projects />
      <GoDown sectionName="contact" />
      <Contact />
    </div>
  );
}
